### ISSUE TITLE
Breaks debug port

### ISSUE THREAD

**Issue by pirj** [WayenWeng/RePhone_SDK_Bin_Update#2]
With this ROM debug port is flooded with garbage

**Comment by WayenWeng** [comment]
The firmware of version 15.19 is for Arduino IDE, it enable the serial output.
The firmware of version 15.29 is for Eclipse IDE, it enable the monitor output.
So, if use the firmware of version 15.29 to Rehone, the Arduino serial port is off, and the Eclipse monitor port is on.

**Comment by pirj** [comment]
Thanks, got it!
